modLoader = "kotlinforforge"
loaderVersion = "[4.11,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "marionetta"
version = "${version}"
displayName = "Valkyrien Skies Addon Template"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.marionetta]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.marionetta]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.marionetta]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.marionetta]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.0,)"
ordering = "AFTER"
side = "BOTH"
